QT       += core gui  network svg xml multimediawidgets qml printsupport webengine webenginewidgets xmlpatterns

greaterThan(QT_MAJOR_VERSION, 4): QT += widgets

CONFIG += c++17
INCLUDEPATH += ./Source \
            C:\Program Files (x86)\Windows Kits\10\include\10.0.22621.0\um\windows.h  \
LIBS += -luser32
# You can make your code fail to compile if it uses deprecated APIs.
# In order to do so, uncomment the following line.
#DEFINES += QT_DISABLE_DEPRECATED_BEFORE=0x060000    # disables all the APIs deprecated before Qt 6.0.0



SOURCES += \
    Source/adaptors/WBCFFAdaptor.cpp \
    Source/adaptors/WBCFFSubsetAdaptor.cpp \
    Source/adaptors/WBExportAdaptor.cpp \
    Source/adaptors/WBExportCFF.cpp \
    Source/adaptors/WBExportDocument.cpp \
    Source/adaptors/WBExportDocumentSetAdaptor.cpp \
    Source/adaptors/WBExportFullPDF.cpp \
    Source/adaptors/WBExportPDF.cpp \
    Source/adaptors/WBExportWeb.cpp \
    Source/adaptors/WBImportAdaptor.cpp \
    Source/adaptors/WBImportCFF.cpp \
    Source/adaptors/WBImportDocument.cpp \
    Source/adaptors/WBImportDocumentSetAdaptor.cpp \
    Source/adaptors/WBImportImage.cpp \
    Source/adaptors/WBImportPDF.cpp \
    Source/adaptors/WBMetadataDcSubsetAdaptor.cpp \
    Source/adaptors/WBSvgSubsetAdaptor.cpp \
    Source/adaptors/WBThumbnailAdaptor.cpp \
    Source/api/WBLibraryAPI.cpp \
    Source/api/WBW3CWidgetAPI.cpp \
    Source/api/WBWidgetMessageAPI.cpp \
    Source/api/WBWidgetUniboardAPI.cpp \
    Source/board/WBBoardController.cpp \
    Source/board/WBBoardPaletteManager.cpp \
    Source/board/WBBoardView.cpp \
    Source/board/WBDrawingController.cpp \
    Source/board/WBFeaturesController.cpp \
    Source/core/WBApplication.cpp \
    Source/core/WBApplicationController.cpp \
    Source/core/WBDisplayManager.cpp \
    Source/core/WBDocumentManager.cpp \
    Source/core/WBDownloadManager.cpp \
    Source/core/WBDownloadThread.cpp \
    Source/core/WBForeignObjectsHandler.cpp \
    Source/core/WBIdleTimer.cpp \
    Source/core/WBMimeData.cpp \
    Source/core/WBOpenSankoreImporter.cpp \
    Source/core/WBPersistenceManager.cpp \
    Source/core/WBPersistenceWorker.cpp \
    Source/core/WBPreferencesController.cpp \
    Source/core/WBSceneCache.cpp \
    Source/core/WBSetting.cpp \
    Source/core/WBSettings.cpp \
    Source/core/WBTextTools.cpp \
    Source/core/main.cpp \
    Source/customWidgets/WBActionableWidget.cpp \
    Source/customWidgets/WBGraphicsItemAction.cpp \
    Source/customWidgets/WBMediaWidget.cpp \
    Source/desktop/WBCustomCaptureWindow.cpp \
    Source/desktop/WBDesktopAnnotationController.cpp \
    Source/desktop/WBDesktopPalette.cpp \
    Source/desktop/WBDesktopPropertyPalette.cpp \
    Source/desktop/WBWindowCaptureDelegate_win.cpp \
    Source/desktop/WBWindowCapture_win.cpp \
    Source/document/WBDocumentContainer.cpp \
    Source/document/WBDocumentController.cpp \
    Source/document/WBDocumentProxy.cpp \
    Source/document/WBSortFilterProxyModel.cpp \
    Source/domain/WBDragableThumbnail.cpp \
    Source/domain/WBGraphicsDelegateFrame.cpp \
    Source/domain/WBGraphicsGroupContainerItem.cpp \
    Source/domain/WBGraphicsGroupContainerItemDelegate.cpp \
    Source/domain/WBGraphicsItemDelegate.cpp \
    Source/domain/WBGraphicsItemGroupUndoCommand.cpp \
    Source/domain/WBGraphicsItemTransformUndoCommand.cpp \
    Source/domain/WBGraphicsItemUndoCommand.cpp \
    Source/domain/WBGraphicsItemZLevelUndoCommand.cpp \
    Source/domain/WBGraphicsMediaItem.cpp \
    Source/domain/WBGraphicsMediaItemDelegate.cpp \
    Source/domain/WBGraphicsPDFItem.cpp \
    Source/domain/WBGraphicsPixmapItem.cpp \
    Source/domain/WBGraphicsPolygonItem.cpp \
    Source/domain/WBGraphicsProxyWidget.cpp \
    Source/domain/WBGraphicsScene.cpp \
    Source/domain/WBGraphicsStroke.cpp \
    Source/domain/WBGraphicsStrokesGroup.cpp \
    Source/domain/WBGraphicsSvgItem.cpp \
    Source/domain/WBGraphicsTextItem.cpp \
    Source/domain/WBGraphicsTextItemDelegate.cpp \
    Source/domain/WBGraphicsTextItemUndoCommand.cpp \
    Source/domain/WBGraphicsWidgetItem.cpp \
    Source/domain/WBGraphicsWidgetItemDelegate.cpp \
    Source/domain/WBItem.cpp \
    Source/domain/WBPageSizeUndoCommand.cpp \
    Source/domain/WBResizableGraphicsItem.cpp \
    Source/domain/WBSelectionFrame.cpp \
    Source/domain/WBUndoCommand.cpp \
    Source/frameworks/WBBase32.cpp \
    Source/frameworks/WBCoreGraphicsScene.cpp \
    Source/frameworks/WBCryptoUtils.cpp \
    Source/frameworks/WBFileSystemUtils.cpp \
    Source/frameworks/WBGeometryUtils.cpp \
    Source/frameworks/WBPlatformUtils.cpp \
    Source/frameworks/WBPlatformUtils_win.cpp \
    Source/frameworks/WBStringUtils.cpp \
    Source/frameworks/WBVersion.cpp \
    Source/gui/WBActionPalette.cpp \
    Source/gui/WBBackgroundPalette.cpp \
    Source/gui/WBBlackoutWidget.cpp \
    Source/gui/WBBoardThumbnailsView.cpp \
    Source/gui/WBCachePropertiesWidget.cpp \
    Source/gui/WBCircleFrame.cpp \
    Source/gui/WBColorPicker.cpp \
    Source/gui/WBDockDownloadWidget.cpp \
    Source/gui/WBDockPalette.cpp \
    Source/gui/WBDockPaletteWidget.cpp \
    Source/gui/WBDocumentNavigator.cpp \
    Source/gui/WBDocumentThumbnailWidget.cpp \
    Source/gui/WBDocumentToolsPalette.cpp \
    Source/gui/WBDocumentTreeWidget.cpp \
    Source/gui/WBDownloadWidget.cpp \
    Source/gui/WBFavoriteToolPalette.cpp \
    Source/gui/WBFeaturesActionBar.cpp \
    Source/gui/WBFeaturesWidget.cpp \
    Source/gui/WBFloatingPalette.cpp \
    Source/gui/WBIconButton.cpp \
    Source/gui/WBKeyboardPalette.cpp \
    Source/gui/WBKeyboardPalette_win.cpp \
    Source/gui/WBLeftPalette.cpp \
    Source/gui/WBMagnifer.cpp \
    Source/gui/WBMainWindow.cpp \
    Source/gui/WBMessageWindow.cpp \
    Source/gui/WBMessagesDialog.cpp \
    Source/gui/WBMousePressFilter.cpp \
    Source/gui/WBOpenSankoreImporterWidget.cpp \
    Source/gui/WBPageNavigationWidget.cpp \
    Source/gui/WBPropertyPalette.cpp \
    Source/gui/WBResources.cpp \
    Source/gui/WBRightPalette.cpp \
    Source/gui/WBRubberBand.cpp \
    Source/gui/WBScreenMirror.cpp \
    Source/gui/WBSpinningWheel.cpp \
    Source/gui/WBStartupHintsPalette.cpp \
    Source/gui/WBStylusPalette.cpp \
    Source/gui/WBThumbnailView.cpp \
    Source/gui/WBThumbnailWidget.cpp \
    Source/gui/WBToolWidget.cpp \
    Source/gui/WBToolbarButtonGroup.cpp \
    Source/gui/WBUpdateDlg.cpp \
    Source/gui/WBWebToolsPalette.cpp \
    Source/gui/WBWidgetMirror.cpp \
    Source/gui/WBZoomPalette.cpp \
    Source/network/WBAutoSaver.cpp \
    Source/network/WBHttpGet.cpp \
    Source/network/WBNetworkAccessManager.cpp \
    Source/pdf-merger/ASCII85Decode.cpp \
    Source/pdf-merger/ASCIIHexDecode.cpp \
    Source/pdf-merger/AnnotsHandler.cpp \
    Source/pdf-merger/CCITTFaxDecode.cpp \
    Source/pdf-merger/ContentHandler.cpp \
    Source/pdf-merger/DCTDecode.cpp \
    Source/pdf-merger/Document.cpp \
    Source/pdf-merger/Filter.cpp \
    Source/pdf-merger/FilterPredictor.cpp \
    Source/pdf-merger/FlateDecode.cpp \
    Source/pdf-merger/JBIG2Decode.cpp \
    Source/pdf-merger/LZWDecode.cpp \
    Source/pdf-merger/Merger.cpp \
    Source/pdf-merger/Object.cpp \
    Source/pdf-merger/OverlayDocumentParser.cpp \
    Source/pdf-merger/Page.cpp \
    Source/pdf-merger/PageElementHandler.cpp \
    Source/pdf-merger/Parser.cpp \
    Source/pdf-merger/Rectangle.cpp \
    Source/pdf-merger/RemoveHimselfHandler.cpp \
    Source/pdf-merger/RunLengthDecode.cpp \
    Source/pdf-merger/Utils.cpp \
    Source/pdf/GraphicsPDFItem.cpp \
    Source/pdf/PDFRenderer.cpp \
    Source/pdf/XPDFRenderer.cpp \
    Source/podcast/WBAbstractVideoEncoder.cpp \
    Source/podcast/WBPodcastController.cpp \
    Source/podcast/WBPodcastRecordingPalette.cpp \
    Source/podcast/windowsmedia/WBWaveRecorder.cpp \
    Source/podcast/windowsmedia/WBWindowsMediaFile.cpp \
    Source/podcast/windowsmedia/WBWindowsMediaVideoEncoder.cpp \
    Source/qtsingleapplication/qtlocalpeer.cpp \
    Source/qtsingleapplication/qtlockedfile.cpp \
    Source/qtsingleapplication/qtlockedfile_win.cpp \
    Source/qtsingleapplication/qtsingleapplication.cpp \
    Source/tools/WBAbstractDrawRuler.cpp \
    Source/tools/WBGraphicsCache.cpp \
    Source/tools/WBGraphicsCompass.cpp \
    Source/tools/WBGraphicsCurtainItem.cpp \
    Source/tools/WBGraphicsCurtainItemDelegate.cpp \
    Source/tools/WBGraphicsProtractor.cpp \
    Source/tools/WBGraphicsRuler.cpp \
    Source/tools/WBGraphicsTriangle.cpp \
    Source/tools/WBToolsManager.cpp \
    Source/web/WBOEmbedParser.cpp \
    Source/web/WBWebController.cpp \
    Source/web/WBWebKitUtils.cpp \
    Source/web/WBWebPage_.cpp \
    Source/web/WBWebPluginWidget.cpp \
    Source/web/browser/WBBrowserWindow.cpp \
    Source/web/browser/WBChaseWidget.cpp \
    Source/web/browser/WBDownloadManager_.cpp \
    Source/web/browser/WBEditTableView.cpp \
    Source/web/browser/WBModelMenu.cpp \
    Source/web/browser/WBSearchLineEdit.cpp \
    Source/web/browser/WBSqueezeLabel.cpp \
    Source/web/browser/WBTabWidget.cpp \
    Source/web/browser/WBToolBarSearch.cpp \
    Source/web/browser/WBUrlLineEdit.cpp \
    Source/web/browser/WBWebTrapWebView.cpp \
    Source/web/browser/WBWebView.cpp


HEADERS += \
    Source/adaptors/WBCFFAdaptor.h \
    Source/adaptors/WBCFFAdaptor_global.h \
    Source/adaptors/WBCFFConstants.h \
    Source/adaptors/WBCFFSubsetAdaptor.h \
    Source/adaptors/WBExportAdaptor.h \
    Source/adaptors/WBExportCFF.h \
    Source/adaptors/WBExportDocument.h \
    Source/adaptors/WBExportDocumentSetAdaptor.h \
    Source/adaptors/WBExportFullPDF.h \
    Source/adaptors/WBExportPDF.h \
    Source/adaptors/WBExportWeb.h \
    Source/adaptors/WBGlobals.h \
    Source/adaptors/WBImportAdaptor.h \
    Source/adaptors/WBImportCFF.h \
    Source/adaptors/WBImportDocument.h \
    Source/adaptors/WBImportDocumentSetAdaptor.h \
    Source/adaptors/WBImportImage.h \
    Source/adaptors/WBImportPDF.h \
    Source/adaptors/WBMetadataDcSubsetAdaptor.h \
    Source/adaptors/WBSvgSubsetAdaptor.h \
    Source/adaptors/WBThumbnailAdaptor.h \
    Source/api/WBLibraryAPI.h \
    Source/api/WBW3CWidgetAPI.h \
    Source/api/WBWidgetMessageAPI.h \
    Source/api/WBWidgetUniboardAPI.h \
    Source/board/WBBoardController.h \
    Source/board/WBBoardPaletteManager.h \
    Source/board/WBBoardView.h \
    Source/board/WBDrawingController.h \
    Source/board/WBFeaturesController.h \
    Source/core/WB.h \
    Source/core/WBApplication.h \
    Source/core/WBApplicationController.h \
    Source/core/WBDisplayManager.h \
    Source/core/WBDocumentManager.h \
    Source/core/WBDownloadManager.h \
    Source/core/WBDownloadThread.h \
    Source/core/WBForeignObjectsHandler.h \
    Source/core/WBIdleTimer.h \
    Source/core/WBMimeData.h \
    Source/core/WBOpenSankoreImporter.h \
    Source/core/WBPersistenceManager.h \
    Source/core/WBPersistenceWorker.h \
    Source/core/WBPreferencesController.h \
    Source/core/WBSceneCache.h \
    Source/core/WBSetting.h \
    Source/core/WBSettings.h \
    Source/core/WBTextTools.h \
    Source/core/memcheck.h \
    Source/core/resource.h \
    Source/customWidgets/WBActionableWidget.h \
    Source/customWidgets/WBGraphicsItemAction.h \
    Source/customWidgets/WBMediaWidget.h \
    Source/desktop/WBCustomCaptureWindow.h \
    Source/desktop/WBDesktopAnnotationController.h \
    Source/desktop/WBDesktopPalette.h \
    Source/desktop/WBDesktopPropertyPalette.h \
    Source/desktop/WBWindowCapture.h \
    Source/desktop/WBWindowCaptureDelegate_win.h \
    Source/document/WBDocumentContainer.h \
    Source/document/WBDocumentController.h \
    Source/document/WBDocumentProxy.h \
    Source/document/WBSortFilterProxyModel.h \
    Source/domain/WBDragableThumbnail.h \
    Source/domain/WBGraphicsDelegateFrame.h \
    Source/domain/WBGraphicsGroupContainerItem.h \
    Source/domain/WBGraphicsGroupContainerItemDelegate.h \
    Source/domain/WBGraphicsItemDelegate.h \
    Source/domain/WBGraphicsItemGroupUndoCommand.h \
    Source/domain/WBGraphicsItemTransformUndoCommand.h \
    Source/domain/WBGraphicsItemUndoCommand.h \
    Source/domain/WBGraphicsItemZLevelUndoCommand.h \
    Source/domain/WBGraphicsMediaItem.h \
    Source/domain/WBGraphicsMediaItemDelegate.h \
    Source/domain/WBGraphicsPDFItem.h \
    Source/domain/WBGraphicsPixmapItem.h \
    Source/domain/WBGraphicsPolygonItem.h \
    Source/domain/WBGraphicsProxyWidget.h \
    Source/domain/WBGraphicsScene.h \
    Source/domain/WBGraphicsStroke.h \
    Source/domain/WBGraphicsStrokesGroup.h \
    Source/domain/WBGraphicsSvgItem.h \
    Source/domain/WBGraphicsTextItem.h \
    Source/domain/WBGraphicsTextItemDelegate.h \
    Source/domain/WBGraphicsTextItemUndoCommand.h \
    Source/domain/WBGraphicsWidgetItem.h \
    Source/domain/WBGraphicsWidgetItemDelegate.h \
    Source/domain/WBItem.h \
    Source/domain/WBPageSizeUndoCommand.h \
    Source/domain/WBResizableGraphicsItem.h \
    Source/domain/WBSelectionFrame.h \
    Source/domain/WBUndoCommand.h \
    Source/frameworks/WBBase32.h \
    Source/frameworks/WBCoreGraphicsScene.h \
    Source/frameworks/WBCryptoUtils.h \
    Source/frameworks/WBFileSystemUtils.h \
    Source/frameworks/WBGeometryUtils.h \
    Source/frameworks/WBPlatformUtils.h \
    Source/frameworks/WBStringUtils.h \
    Source/frameworks/WBVersion.h \
    Source/globals/WBGlobals.h \
    Source/gui/WBActionPalette.h \
    Source/gui/WBBackgroundPalette.h \
    Source/gui/WBBlackoutWidget.h \
    Source/gui/WBBoardThumbnailsView.h \
    Source/gui/WBCachePropertiesWidget.h \
    Source/gui/WBCircleFrame.h \
    Source/gui/WBClockPalette.h \
    Source/gui/WBColorPicker.h \
    Source/gui/WBDockDownloadWidget.h \
    Source/gui/WBDockPalette.h \
    Source/gui/WBDockPaletteWidget.h \
    Source/gui/WBDocumentNavigator.h \
    Source/gui/WBDocumentThumbnailWidget.h \
    Source/gui/WBDocumentToolsPalette.h \
    Source/gui/WBDocumentTreeWidget.h \
    Source/gui/WBDownloadWidget.h \
    Source/gui/WBFavoriteToolPalette.h \
    Source/gui/WBFeaturesActionBar.h \
    Source/gui/WBFeaturesWidget.h \
    Source/gui/WBFloatingPalette.h \
    Source/gui/WBIconButton.h \
    Source/gui/WBKeyboardPalette.h \
    Source/gui/WBLeftPalette.h \
    Source/gui/WBMagnifer.h \
    Source/gui/WBMainWindow.h \
    Source/gui/WBMessageWindow.h \
    Source/gui/WBMessagesDialog.h \
    Source/gui/WBMousePressFilter.h \
    Source/gui/WBOpenSankoreImporterWidget.h \
    Source/gui/WBPageNavigationWidget.h \
    Source/gui/WBPropertyPalette.h \
    Source/gui/WBResources.h \
    Source/gui/WBRightPalette.h \
    Source/gui/WBRubberBand.h \
    Source/gui/WBScreenMirror.h \
    Source/gui/WBSpinningWheel.h \
    Source/gui/WBStartupHintsPalette.h \
    Source/gui/WBStylusPalette.h \
    Source/gui/WBThumbnailView.h \
    Source/gui/WBThumbnailWidget.h \
    Source/gui/WBToolWidget.h \
    Source/gui/WBToolbarButtonGroup.h \
    Source/gui/WBUpdateDlg.h \
    Source/gui/WBWebToolsPalette.h \
    Source/gui/WBWidgetMirror.h \
    Source/gui/WBZoomPalette.h \
    Source/network/WBAutoSaver.h \
    Source/network/WBHttpGet.h \
    Source/network/WBNetworkAccessManager.h \
    Source/pdf-merger/ASCII85Decode.h \
    Source/pdf-merger/ASCIIHexDecode.h \
    Source/pdf-merger/AbstractBoxElementHandler.h \
    Source/pdf-merger/AnnotsHandler.h \
    Source/pdf-merger/CCITTFaxDecode.h \
    Source/pdf-merger/Config.h \
    Source/pdf-merger/ContentHandler.h \
    Source/pdf-merger/CropBoxElementHandler.h \
    Source/pdf-merger/DCTDecode.h \
    Source/pdf-merger/Decoder.h \
    Source/pdf-merger/Document.h \
    Source/pdf-merger/Exception.h \
    Source/pdf-merger/FileIsAbsentException.h \
    Source/pdf-merger/Filter.h \
    Source/pdf-merger/FilterPredictor.h \
    Source/pdf-merger/FlateDecode.h \
    Source/pdf-merger/JBIG2Decode.h \
    Source/pdf-merger/LZWDecode.h \
    Source/pdf-merger/MediaBoxElementHandler.h \
    Source/pdf-merger/MergePageDescription.h \
    Source/pdf-merger/Merger.h \
    Source/pdf-merger/Object.h \
    Source/pdf-merger/OverlayDocumentParser.h \
    Source/pdf-merger/Page.h \
    Source/pdf-merger/PageElementHandler.h \
    Source/pdf-merger/PageParser.h \
    Source/pdf-merger/Parser.h \
    Source/pdf-merger/Rectangle.h \
    Source/pdf-merger/RemoveHimSelfHandler.h \
    Source/pdf-merger/RotationHandler.h \
    Source/pdf-merger/RunLengthDecode.h \
    Source/pdf-merger/Transformation.h \
    Source/pdf-merger/TypeElementHandler.h \
    Source/pdf-merger/Utils.h \
    Source/pdf/GraphicsPDFItem.h \
    Source/pdf/PDFRenderer.h \
    Source/pdf/XPDFRenderer.h \
    Source/podcast/WBAbstractVideoEncoder.h \
    Source/podcast/WBPodcastController.h \
    Source/podcast/WBPodcastRecordingPalette.h \
    Source/podcast/windowsmedia/WBWaveRecorder.h \
    Source/podcast/windowsmedia/WBWindowsMediaFile.h \
    Source/podcast/windowsmedia/WBWindowsMediaVideoEncoder.h \
    Source/qtsingleapplication/qtlocalpeer.h \
    Source/qtsingleapplication/qtlockedfile.h \
    Source/qtsingleapplication/qtsingleapplication.h \
    Source/tools/WBAbstractDrawRuler.h \
    Source/tools/WBGraphicsCache.h \
    Source/tools/WBGraphicsCompass.h \
    Source/tools/WBGraphicsCurtainItem.h \
    Source/tools/WBGraphicsCurtainItemDelegate.h \
    Source/tools/WBGraphicsProtractor.h \
    Source/tools/WBGraphicsRuler.h \
    Source/tools/WBGraphicsTriangle.h \
    Source/tools/WBToolsManager.h \
    Source/web/WBOEmbedParser.h \
    Source/web/WBWebController.h \
    Source/web/WBWebKitUtils.h \
    Source/web/WBWebPage_.h \
    Source/web/WBWebPluginWidget.h \
    Source/web/browser/WBBrowserWindow.h \
    Source/web/browser/WBChaseWidget.h \
    Source/web/browser/WBDownloadManager_.h \
    Source/web/browser/WBEditTableView.h \
    Source/web/browser/WBModelMenu.h \
    Source/web/browser/WBSearchLineEdit.h \
    Source/web/browser/WBSqueezeLabel.h \
    Source/web/browser/WBTabWidget.h \
    Source/web/browser/WBToolBarSearch.h \
    Source/web/browser/WBUrlLineEdit.h \
    Source/web/browser/WBWebTrapWebView.h \
    Source/web/browser/WBWebView.h

FORMS += \
    Source/web/browser/downloaditem.ui \
    Source/web/browser/downloads.ui \
    Source/web/browser/proxy.ui \
    UI/blackoutWidget.ui \
    UI/brushProperties.ui \
    UI/documents.ui \
    UI/mainWindow.ui \
    UI/preferences.ui

# Default rules for deployment.
qnx: target.path = /tmp/$${TARGET}/bin
else: unix:!android: target.path = /opt/$${TARGET}/bin
!isEmpty(target.path): INSTALLS += target

RESOURCES += \
    Resources/WBoard.qrc

DISTFILES += \
    Resources/customizations/fonts/AndBasR.ttf \
    Resources/customizations/fonts/Bstgreek.ttf \
    Resources/customizations/fonts/EcritureA-Italique-Ligne.otf \
    Resources/customizations/fonts/EcritureA-Italique-Orne-Ligne.otf \
    Resources/customizations/fonts/EcritureA-Italique-Orne.otf \
    Resources/customizations/fonts/EcritureA-Italique.otf \
    Resources/customizations/fonts/EcritureA-Romain-Ligne.otf \
    Resources/customizations/fonts/EcritureA-Romain-Orne-Ligne.otf \
    Resources/customizations/fonts/EcritureA-Romain-Orne.otf \
    Resources/customizations/fonts/EcritureA-Romain.otf \
    Resources/customizations/fonts/EcritureB-Italique-Ligne.otf \
    Resources/customizations/fonts/EcritureB-Italique-Orne-Ligne.otf \
    Resources/customizations/fonts/EcritureB-Italique-Orne.otf \
    Resources/customizations/fonts/EcritureB-Italique.otf \
    Resources/customizations/fonts/EcritureB-Romain-Ligne.otf \
    Resources/customizations/fonts/EcritureB-Romain-Orne-Ligne.otf \
    Resources/customizations/fonts/EcritureB-Romain-Orne.otf \
    Resources/customizations/fonts/EcritureB-Romain.otf \
    Resources/customizations/fonts/GETypoLibre.otf \
    Resources/customizations/fonts/ec_cour.ttf \
    Resources/customizations/fonts/ecl_cour.ttf \
    Resources/etc/WBoard.css \
    Resources/etc/freezedWidgetWrapper.html \
    Resources/etc/img/loading.gif \
    Resources/etc/intranet-podcast-metadata.template \
    Resources/etc/npapi-wrapper.application.x-shockwave-flash.swf.htm \
    Resources/etc/npapi-wrapper.config.xml \
    Resources/fonts/COPYRIGHT \
    Resources/fonts/d050000l.pfb \
    Resources/fonts/n019003l.pfb \
    Resources/fonts/n019004l.pfb \
    Resources/fonts/n019023l.pfb \
    Resources/fonts/n019024l.pfb \
    Resources/fonts/n021003l.pfb \
    Resources/fonts/n021004l.pfb \
    Resources/fonts/n021023l.pfb \
    Resources/fonts/n021024l.pfb \
    Resources/fonts/n022003l.pfb \
    Resources/fonts/n022004l.pfb \
    Resources/fonts/n022023l.pfb \
    Resources/fonts/n022024l.pfb \
    Resources/fonts/s050000l.pfb \
    Resources/images/WBoard.png \
    Resources/images/addItemToCurrentPage.svg \
    Resources/images/addItemToLibrary.svg \
    Resources/images/addItemToNewPage.svg \
    Resources/images/angleMarker.svg \
    Resources/images/asc.png \
    Resources/images/backgroundPalette/background1.svg \
    Resources/images/backgroundPalette/background1On.svg \
    Resources/images/backgroundPalette/background2.svg \
    Resources/images/backgroundPalette/background2On.svg \
    Resources/images/backgroundPalette/background3.svg \
    Resources/images/backgroundPalette/background3On.svg \
    Resources/images/backgroundPalette/background4.svg \
    Resources/images/backgroundPalette/background4On.svg \
    Resources/images/backgroundPalette/background5.svg \
    Resources/images/backgroundPalette/background5On.svg \
    Resources/images/backgroundPalette/background6.svg \
    Resources/images/backgroundPalette/background6On.svg \
    Resources/images/backgroundPalette/resetDefaultGridSize.svg \
    Resources/images/bigOpenBoard.png \
    Resources/images/cache_circle.png \
    Resources/images/cache_square.png \
    Resources/images/centerAligned.svg \
    Resources/images/circle.svg \
    Resources/images/close.svg \
    Resources/images/closeDisabled.svg \
    Resources/images/closeTool.svg \
    Resources/images/collapse-all.png \
    Resources/images/color.svg \
    Resources/images/currentDocument.png \
    Resources/images/cursors/drawCompass.png \
    Resources/images/cursors/drawRulerLine.png \
    Resources/images/cursors/eraser.png \
    Resources/images/cursors/laser.png \
    Resources/images/cursors/marker.png \
    Resources/images/cursors/play.png \
    Resources/images/cursors/resize.png \
    Resources/images/cursors/rotate.png \
    Resources/images/cursors/zoomIn.png \
    Resources/images/cursors/zoomOut.png \
    Resources/images/decrease.svg \
    Resources/images/defaultWidgetIcon.png \
    Resources/images/desc.png \
    Resources/images/down_arrow.png \
    Resources/images/duplicate.svg \
    Resources/images/duplicateDisabled.svg \
    Resources/images/edit-mode.png \
    Resources/images/edit-mode.svg \
    Resources/images/erasePalette/eraseAll.svg \
    Resources/images/erasePalette/eraseAnnotation.svg \
    Resources/images/erasePalette/eraseBackground.svg \
    Resources/images/erasePalette/eraseItem.svg \
    Resources/images/expand-all.png \
    Resources/images/extraPalette/blackout.png \
    Resources/images/extraPalette/blackoutOn.png \
    Resources/images/extraPalette/compass.png \
    Resources/images/extraPalette/compassOn.png \
    Resources/images/extraPalette/keyboard.png \
    Resources/images/extraPalette/keyboardOn.png \
    Resources/images/extraPalette/mask.png \
    Resources/images/extraPalette/maskOn.png \
    Resources/images/extraPalette/oEmbed.png \
    Resources/images/extraPalette/podcast.png \
    Resources/images/extraPalette/podcastOn.png \
    Resources/images/extraPalette/protractor.png \
    Resources/images/extraPalette/protractorOn.png \
    Resources/images/extraPalette/ruler.png \
    Resources/images/extraPalette/rulerOn.png \
    Resources/images/extraPalette/trapFlash.png \
    Resources/images/extraPalette/webTrap.png \
    Resources/images/extraPalette/webTrapEnabled.png \
    Resources/images/eyeClosed.svg \
    Resources/images/eyeOpened.svg \
    Resources/images/favorites.png \
    Resources/images/flags/en.png \
    Resources/images/flags/zh-hans.png \
    Resources/images/flash.svg \
    Resources/images/folder.png \
    Resources/images/font.svg \
    Resources/images/frozen.svg \
    Resources/images/general_close.png \
    Resources/images/general_open.png \
    Resources/images/groupItems.svg \
    Resources/images/hflipTool.svg \
    Resources/images/home.svg \
    Resources/images/increase.svg \
    Resources/images/leftAligned.svg \
    Resources/images/left_arrow.png \
    Resources/images/libpalette/ApplicationsCategory.svg \
    Resources/images/libpalette/AudiosCategory.svg \
    Resources/images/libpalette/FavoritesCategory.svg \
    Resources/images/libpalette/InteractivesCategory.svg \
    Resources/images/libpalette/MoviesCategory.svg \
    Resources/images/libpalette/PicturesCategory.svg \
    Resources/images/libpalette/ShapesCategory.svg \
    Resources/images/libpalette/TrashCategory.svg \
    Resources/images/libpalette/WebSearchCategory.svg \
    Resources/images/libpalette/back.png \
    Resources/images/libpalette/folder.svg \
    Resources/images/libpalette/home.png \
    Resources/images/libpalette/loading.png \
    Resources/images/libpalette/miniFavorite.png \
    Resources/images/libpalette/miniNewFolder.png \
    Resources/images/libpalette/miniSearch.png \
    Resources/images/libpalette/miniTrash.png \
    Resources/images/libpalette/movieIcon.svg \
    Resources/images/libpalette/notFound.png \
    Resources/images/libpalette/social.png \
    Resources/images/libpalette/soundIcon.svg \
    Resources/images/libpalette/trash_favorite.svg \
    Resources/images/lock.svg \
    Resources/images/locked.svg \
    Resources/images/menu.svg \
    Resources/images/menuDisabled.svg \
    Resources/images/minus.svg \
    Resources/images/moveDown.svg \
    Resources/images/moveDownDisabled.svg \
    Resources/images/moveUp.svg \
    Resources/images/moveUpDisabled.svg \
    Resources/images/myContent.png \
    Resources/images/myfolder.png \
    Resources/images/navig_arrow.png \
    Resources/images/notAligned.svg \
    Resources/images/online.png \
    Resources/images/pause.svg \
    Resources/images/pin.svg \
    Resources/images/play.svg \
    Resources/images/plus.svg \
    Resources/images/reload.svg \
    Resources/images/resetAngle.svg \
    Resources/images/resetTool.svg \
    Resources/images/resize.svg \
    Resources/images/resizeBottom.svg \
    Resources/images/resizeButton.svg \
    Resources/images/resizeCompass.svg \
    Resources/images/resizeLeft.svg \
    Resources/images/resizeRight.svg \
    Resources/images/resizeRuler.svg \
    Resources/images/resizeTool.svg \
    Resources/images/resizeTop.svg \
    Resources/images/rightAligned.svg \
    Resources/images/right_arrow.png \
    Resources/images/rotate.svg \
    Resources/images/rotateProtractor.svg \
    Resources/images/rotateTool.svg \
    Resources/images/roundeRrectangle.svg \
    Resources/images/save.png \
    Resources/images/save.svg \
    Resources/images/setAsBackground.svg \
    Resources/images/shape.png \
    Resources/images/soundOff.svg \
    Resources/images/soundOn.svg \
    Resources/images/stop.svg \
    Resources/images/stylusPalette/arrow.png \
    Resources/images/stylusPalette/arrowOn.png \
    Resources/images/stylusPalette/captureArea.png \
    Resources/images/stylusPalette/captureAreaOn.png \
    Resources/images/stylusPalette/eraser.png \
    Resources/images/stylusPalette/eraserArrow.png \
    Resources/images/stylusPalette/eraserOn.png \
    Resources/images/stylusPalette/eraserOnArrow.png \
    Resources/images/stylusPalette/hand.png \
    Resources/images/stylusPalette/handOn.png \
    Resources/images/stylusPalette/handPlay.png \
    Resources/images/stylusPalette/handPlayOn.png \
    Resources/images/stylusPalette/laser.png \
    Resources/images/stylusPalette/laserOn.png \
    Resources/images/stylusPalette/line.png \
    Resources/images/stylusPalette/lineOn.png \
    Resources/images/stylusPalette/marker.png \
    Resources/images/stylusPalette/markerArrow.png \
    Resources/images/stylusPalette/markerOn.png \
    Resources/images/stylusPalette/markerOnArrow.png \
    Resources/images/stylusPalette/pen.png \
    Resources/images/stylusPalette/penArrow.png \
    Resources/images/stylusPalette/penOn.png \
    Resources/images/stylusPalette/penOnArrow.png \
    Resources/images/stylusPalette/restoreZoom.png \
    Resources/images/stylusPalette/text.png \
    Resources/images/stylusPalette/textOn.png \
    Resources/images/stylusPalette/zoomIn.png \
    Resources/images/stylusPalette/zoomInOn.png \
    Resources/images/stylusPalette/zoomOut.png \
    Resources/images/stylusPalette/zoomOutOn.png \
    Resources/images/tab_mask.png \
    Resources/images/toolPalette/cacheTool.png \
    Resources/images/toolPalette/compassTool.png \
    Resources/images/toolPalette/magnifierTool.png \
    Resources/images/toolPalette/maskTool.png \
    Resources/images/toolPalette/protractorTool.png \
    Resources/images/toolPalette/rulerTool.png \
    Resources/images/toolPalette/triangleTool.png \
    Resources/images/toolbar/addBookmark.png \
    Resources/images/toolbar/addInteractiveToLibrary.png \
    Resources/images/toolbar/addToDocument.png \
    Resources/images/toolbar/addToLibrary.png \
    Resources/images/toolbar/addToPage.png \
    Resources/images/toolbar/addToWorkingDoc.png \
    Resources/images/toolbar/addToolToLibrary.png \
    Resources/images/toolbar/background.png \
    Resources/images/toolbar/board.png \
    Resources/images/toolbar/boardOn.png \
    Resources/images/toolbar/bookmarks.png \
    Resources/images/toolbar/captureArea.png \
    Resources/images/toolbar/captureAreaOn.png \
    Resources/images/toolbar/captureScreen.png \
    Resources/images/toolbar/captureScreenOn.png \
    Resources/images/toolbar/captureWindow.png \
    Resources/images/toolbar/clearPage.png \
    Resources/images/toolbar/color.png \
    Resources/images/toolbar/copy.png \
    Resources/images/toolbar/cut.png \
    Resources/images/toolbar/deleteDocument.png \
    Resources/images/toolbar/deleteFolder.png \
    Resources/images/toolbar/display.png \
    Resources/images/toolbar/documents.png \
    Resources/images/toolbar/duplicate.png \
    Resources/images/toolbar/eraserTool.png \
    Resources/images/toolbar/export.png \
    Resources/images/toolbar/extraTool.png \
    Resources/images/toolbar/eyeClosed.png \
    Resources/images/toolbar/eyeOpened.png \
    Resources/images/toolbar/group.png \
    Resources/images/toolbar/hide.png \
    Resources/images/toolbar/home.png \
    Resources/images/toolbar/import.png \
    Resources/images/toolbar/largeEraser.png \
    Resources/images/toolbar/largePen.png \
    Resources/images/toolbar/library.png \
    Resources/images/toolbar/lineTool.png \
    Resources/images/toolbar/mediumEraser.png \
    Resources/images/toolbar/mediumPen.png \
    Resources/images/toolbar/menu.png \
    Resources/images/toolbar/mic.png \
    Resources/images/toolbar/micOff.png \
    Resources/images/toolbar/newDocument.png \
    Resources/images/toolbar/newFolder.png \
    Resources/images/toolbar/newPage.png \
    Resources/images/toolbar/next.png \
    Resources/images/toolbar/nextPageOn.png \
    Resources/images/toolbar/open.png \
    Resources/images/toolbar/pageSize.png \
    Resources/images/toolbar/paste.png \
    Resources/images/toolbar/pause.png \
    Resources/images/toolbar/pdf.png \
    Resources/images/toolbar/plusBlack.png \
    Resources/images/toolbar/plusBlackOn.png \
    Resources/images/toolbar/previous.png \
    Resources/images/toolbar/previousPageOn.png \
    Resources/images/toolbar/print.png \
    Resources/images/toolbar/profile.png \
    Resources/images/toolbar/proto.png \
    Resources/images/toolbar/quit.png \
    Resources/images/toolbar/quitOn.png \
    Resources/images/toolbar/record.png \
    Resources/images/toolbar/redo.png \
    Resources/images/toolbar/redoOn.png \
    Resources/images/toolbar/reload.png \
    Resources/images/toolbar/remove.png \
    Resources/images/toolbar/removeBackground.png \
    Resources/images/toolbar/rename.png \
    Resources/images/toolbar/setBackground.png \
    Resources/images/toolbar/settings.png \
    Resources/images/toolbar/smallEraser.png \
    Resources/images/toolbar/smallPen.png \
    Resources/images/toolbar/smallerText.png \
    Resources/images/toolbar/softwareUpdate.png \
    Resources/images/toolbar/stop.png \
    Resources/images/toolbar/stylus.png \
    Resources/images/toolbar/stylusTab.png \
    Resources/images/toolbar/tools.png \
    Resources/images/toolbar/tutorial.png \
    Resources/images/toolbar/undo.png \
    Resources/images/toolbar/undoOn.png \
    Resources/images/toolbar/ungroup.png \
    Resources/images/toolbar/updates.png \
    Resources/images/toolbar/web.png \
    Resources/images/toolbar/webTrap.png \
    Resources/images/toolbar/webTrapEnabled.png \
    Resources/images/toolbar/webUpload.png \
    Resources/images/toolbar/window.png \
    Resources/images/tools.png \
    Resources/images/trash.png \
    Resources/images/unfrozen.svg \
    Resources/images/ungroupItems.svg \
    Resources/images/unlock.svg \
    Resources/images/unlocked.svg \
    Resources/images/unpin.svg \
    Resources/images/up_arrow.png \
    Resources/images/vflipTool.svg \
    Resources/images/virtual.keyboard/29/backspace.png \
    Resources/images/virtual.keyboard/29/capslock.png \
    Resources/images/virtual.keyboard/29/centre-active.png \
    Resources/images/virtual.keyboard/29/centre-passive.png \
    Resources/images/virtual.keyboard/29/left-active.png \
    Resources/images/virtual.keyboard/29/left-passive.png \
    Resources/images/virtual.keyboard/29/right-active.png \
    Resources/images/virtual.keyboard/29/right-passive.png \
    Resources/images/virtual.keyboard/29/shift.png \
    Resources/images/virtual.keyboard/29/tab.png \
    Resources/images/virtual.keyboard/41/backspace.png \
    Resources/images/virtual.keyboard/41/capslock.png \
    Resources/images/virtual.keyboard/41/centre-active.png \
    Resources/images/virtual.keyboard/41/centre-passive.png \
    Resources/images/virtual.keyboard/41/left-active.png \
    Resources/images/virtual.keyboard/41/left-passive.png \
    Resources/images/virtual.keyboard/41/right-active.png \
    Resources/images/virtual.keyboard/41/right-passive.png \
    Resources/images/virtual.keyboard/41/shift.png \
    Resources/images/virtual.keyboard/41/tab.png \
    Resources/images/z_layer_down.svg \
    Resources/images/z_layer_up.svg \
    Resources/library/pictures/Worldmap_wdb_combined.svg \
    Resources/library/shape/blue_arrow_down.svg \
    Resources/library/shape/blue_arrow_left.svg \
    Resources/library/shape/blue_arrow_right.svg \
    Resources/library/shape/blue_arrow_up.svg \
    Resources/library/shape/blue_bubble_speak.svg \
    Resources/library/shape/blue_bubble_speak_left.svg \
    Resources/library/shape/blue_bubble_think.svg \
    Resources/library/shape/blue_cylinder.svg \
    Resources/library/shape/blue_disk.svg \
    Resources/library/shape/blue_exagon.svg \
    Resources/library/shape/blue_pentagon.svg \
    Resources/library/shape/blue_rectangle.svg \
    Resources/library/shape/blue_rectangle_rnd.svg \
    Resources/library/shape/blue_square.svg \
    Resources/library/shape/blue_square_rnd.svg \
    Resources/library/shape/blue_star.svg \
    Resources/library/shape/blue_star_rnd.svg \
    Resources/library/shape/blue_triangle.svg \
    Resources/library/shape/blue_triangle_rnd.svg \
    Resources/library/shape/grey_arrow_down.svg \
    Resources/library/shape/grey_arrow_left.svg \
    Resources/library/shape/grey_arrow_right.svg \
    Resources/library/shape/grey_arrow_up.svg \
    Resources/library/shape/grey_bubble_speak.svg \
    Resources/library/shape/grey_bubble_speak_left.svg \
    Resources/library/shape/grey_bubble_think.svg \
    Resources/library/shape/grey_cylinder.svg \
    Resources/library/shape/grey_disk.svg \
    Resources/library/shape/grey_exagon.svg \
    Resources/library/shape/grey_pentagon.svg \
    Resources/library/shape/grey_rectangle.svg \
    Resources/library/shape/grey_rectangle_rnd.svg \
    Resources/library/shape/grey_square.svg \
    Resources/library/shape/grey_square_rnd.svg \
    Resources/library/shape/grey_star.svg \
    Resources/library/shape/grey_star_rnd.svg \
    Resources/library/shape/grey_triangle.svg \
    Resources/library/shape/grey_triangle_rnd.svg \
    Resources/library/shape/nofill_arrow_down.svg \
    Resources/library/shape/nofill_arrow_left.svg \
    Resources/library/shape/nofill_arrow_right.svg \
    Resources/library/shape/nofill_arrow_up.svg \
    Resources/library/shape/nofill_bubble_speak.svg \
    Resources/library/shape/nofill_bubble_speak_left.svg \
    Resources/library/shape/nofill_bubble_think.svg \
    Resources/library/shape/nofill_cylinder.svg \
    Resources/library/shape/nofill_disk.svg \
    Resources/library/shape/nofill_exagon.svg \
    Resources/library/shape/nofill_octogon.svg \
    Resources/library/shape/nofill_pentagon.svg \
    Resources/library/shape/nofill_rectangle.svg \
    Resources/library/shape/nofill_rectangle_rnd.svg \
    Resources/library/shape/nofill_rhombus.svg \
    Resources/library/shape/nofill_square.svg \
    Resources/library/shape/nofill_square_rnd.svg \
    Resources/library/shape/nofill_star.svg \
    Resources/library/shape/nofill_star_rnd.svg \
    Resources/library/shape/nofill_trapeze.svg \
    Resources/library/shape/nofill_triangle.svg \
    Resources/library/shape/nofill_triangle_rect.svg \
    Resources/library/shape/nofill_triangle_rnd.svg \
    Resources/library/shape/red_arrow_down.svg \
    Resources/library/shape/red_arrow_left.svg \
    Resources/library/shape/red_arrow_right.svg \
    Resources/library/shape/red_arrow_up.svg \
    Resources/library/shape/red_bubble_speak.svg \
    Resources/library/shape/red_bubble_speak_left.svg \
    Resources/library/shape/red_bubble_think.svg \
    Resources/library/shape/red_cylinder.svg \
    Resources/library/shape/red_disk.svg \
    Resources/library/shape/red_exagon.svg \
    Resources/library/shape/red_pentagon.svg \
    Resources/library/shape/red_rectangle.svg \
    Resources/library/shape/red_rectangle_rnd.svg \
    Resources/library/shape/red_square.svg \
    Resources/library/shape/red_square_rnd.svg \
    Resources/library/shape/red_star.svg \
    Resources/library/shape/red_star_rnd.svg \
    Resources/library/shape/red_triangle.svg \
    Resources/library/shape/red_triangle_rnd.svg \
    Resources/library/shape/white_arrow_down.svg \
    Resources/library/shape/white_arrow_left.svg \
    Resources/library/shape/white_arrow_right.svg \
    Resources/library/shape/white_arrow_up.svg \
    Resources/library/shape/white_bubble_speak.svg \
    Resources/library/shape/white_bubble_speak_left.svg \
    Resources/library/shape/white_bubble_think.svg \
    Resources/library/shape/white_cylinder.svg \
    Resources/library/shape/white_disk.svg \
    Resources/library/shape/white_exagon.svg \
    Resources/library/shape/white_pentagon.svg \
    Resources/library/shape/white_rectangle.svg \
    Resources/library/shape/white_rectangle_rnd.svg \
    Resources/library/shape/white_square.svg \
    Resources/library/shape/white_square_rnd.svg \
    Resources/library/shape/white_star.svg \
    Resources/library/shape/white_star_rnd.svg \
    Resources/library/shape/white_triangle.svg \
    Resources/library/shape/white_triangle_rnd.svg \
    Resources/podcast/WBoard.prx \
    Resources/style.qss \
    Resources/style/treeview-branch-closed.png \
    Resources/style/treeview-branch-open.png \
    Resources/webbrowser/closetab.png \
    Resources/webbrowser/loading.gif \
    Resources/webbrowser/notfound.html \
    Resources/webbrowser/object-wrapper.html \
    Resources/win/OpenBoardDoc.ico
